export default {
    locale: 'en-US',  
    'en-US': {
       tab: {
       	ecology: 'Ecological construction',
       	user: 'Mine',
       	trade: 'transaction',
       	wallet: 'Home'
       },
       page: {
       	news: 'Message',
       	createWallet: 'Create',
       	backup: 'Backup mnemonic',
       	confirm: 'Confirm mnemonic',
       	restore: 'Import Identity',
       	power: 'Power Source',
       	asset: 'Asset List',
       	creditcode: 'Credit Token',
       	nodecode: 'Node Code',
       	setting: 'Set',
       	about: 'About us',
       	walletActive: 'Activate account',
       	exchange: 'Cross link transformation',
       	exchangeDetail: 'Detail',
       	userAccount: 'Account management',
       	accountlist: 'All sub accounts',
       	subAccount: 'Sub account',
       	createAccount: 'Create account',
       	userExchange: 'Exchange',
       	feedBack: 'Message center',
       	personal: 'Personal data',
       	safe: 'Safety Center',
       	settingpw: 'Password settings',
       	team: 'My Team',
       	transfer: 'Transfer',
       	recordDetail: 'Transaction details',
       	settingPaypw: 'Payment password setting',
		USDFExchange:'USDF Exchange',
		exchageRecord: 'exchange record',
		USDFTransaction:'USDF transaction'
       },
       common: {
       	unopen: 'Not yet open',
       	remenberTip: 'Friendship Tip',
       	enterPw: 'enter a password',
       	copySuccess: 'Copy to clipboard',
       	version: 'Version',
       	warmTip: 'Warm Tips',
       	safeTitle: 'Safe Authentication',
       	safePassword: 'Password',
       	loginPw: 'login password',
       	enterSafePwd: 'Please enter security password',
       	submitBtn: 'Submit',
       	pwVal: 'Password length must be 8-16 digits',
       	pwDiff: 'Inconsistent input twice',
       	refresh: 'Pull up to show more',
       	loading: 'Loading...',
       	noMore: 'No more data',
       	cancel: 'cancel',
       	confirm: 'determine',
       	getCode: 'Send',
       	waiting: 'please wait patiently',
       	noCoin: 'No currency available',
       	paymentPassword: 'Please enter the payment password',
       	unableModify: 'not editable',
       	settingPaymentFirst: 'Please set the fund password first'
       },
       lang: {
       	chose: 'Language',
       	clearStore: 'Clear cache',
       	clearSuccess: 'Cleared successfully',
       	cancel: 'Cancel',
       	exit: 'Retreat safely'
       },
       user: {
       	identManager: 'IdentManager',
       	deleteText: 'Delete',
       	payment: 'payment method',
       	paymentCode: 'Receipt Code',
       	creditCode: 'Credit Token',
       	nodeCode: 'Node Code',
       	copyAddress: 'Copy Address',
       	aeed: 'Mnemonic',
       	outputKey: 'Export Private Key',
       	privateKey: 'Private Key',
       	output: 'Export',
       	outputSeed: 'Export mnemonic',
       	deleteTip: 'Are you sure you want to delete the account? ',
       	createSub: 'Create Sub Account',
       	switchConfirm: 'Are you sure you want to switch accounts? ',
       	current: 'Current',
       	currentAccount: 'Current',
       	collectConfirm: 'Will the child account USDF collect the master account? ',
       	viewAllAccount: 'View all subaccounts',
       	subAccountTip: 'Creating a sub-account requires activation to complete the creation. The sub-account will be bound to the master account for life. The operation of the sub-account will be completed by switching the master account. And the sub-account subscription and creation amount are all deducted from the main account funds. ',
       	oneStepCollect: 'collection',
       	usernameOrAddress: 'Account/Address',
       	realSwitch: 'Tap account switch',
       	manager: 'Manage',
       	otherOption: 'Other operations',
       	createAccount: 'Create Account',
       	inputAccount: 'Import Account',
       	addressBook: 'Address Book',
       	newCreate: 'New',
       	addressDetail: 'Address Details',
       	edit: 'Edit',
       	deleteAddress: 'Delete address',
       	createAddress: 'New Address',
       	save: 'Save',
       	enterAddress: 'Enter a valid address',
       	addressName: 'Name',
       	addressNote: 'Description (optional)',
		"addressNoteDetail": "Remarks",
		"addressNameDetail": "Address",
       	enterAddressName: 'Enter Name',
       	accountName: 'Account',
       	enterAccountName: 'Enter Account',
       	walletPassword: 'Wallet Password',
       	enterWalletPw: 'Enter password',
       	confirmPw: 'Confirm Password',
       	repeatEnterPw: 'Repeat the password',
       	create: 'Create',
       	avalible: 'Available',
       	avalibleQuote: 'Available Quota',
       	creditRecord: 'Credit Record',
       	interchange: 'mutual transfer',
       	exchange: 'Exchange',
       	fromText: 'From',
       	toText: 'to',
       	exchangeOutNum: 'Number of transfers',
       	enteerExchangeNum: 'Number of inputs',
       	all: 'All',
       	balance: 'Balance',
       	rate: 'Exchange rate',
       	question: 'Question',
       	serviceReplay: 'Reply',
       	serviceNote: "Customer Service Message",
       	noReplay: 'No reply yet',
       	viewSubAccount: 'SubAccount',
       	myTeam: 'My Team',
       	relationship: 'Node relationship',
       	accountMananger: 'Account Management',
       	safeCenter: 'Safe Center',
       	contactUs: 'Contact Us',
       	inviteFriend: 'Invite a friend',
       	myLeftCode: 'Entropy increas node code',
       	myRightCode: 'Entropy minus node code',
       	level: 'Level',
       	leftCode: 'increas',
       	rightCode: 'minus',
       	copy: 'Copy',
       	avatar: 'Avatar',
       	nickname: 'nickname',
       	enterNickname: 'Enter Nickname',
       	mobile: 'Mobile',
		enterMobile:' Enter Mobile',
       	email: 'Email',
       	modify: 'Modify',
       	toBind: 'Go Bind',
       	newsCenter: 'Message',
       	feedbackQuestion: 'Question for input feedback',
       	feedbackContent: 'Enter feedback content and suggestions ...',
       	feedbackSubmit: 'Submit Feedback',
		"moreMessage":'more',
       	completeInfo: 'Enter complete information',
       	valCode: 'Verification Code',
       	pleaseEnter: 'Enter',
       	enterValCode: 'Fill in the verification code',
       	confirm: 'Confirm',
       	mobileBinding: 'Mobile binding',
       	emailBinding: 'Email binding',
       	mobileError: 'The format of the mobile phone number is incorrect',
       	emailError: 'Mailbox format error',
       	numCode: 'Enter a 6-digit verification code',
       	oldPw: 'Old Password',
       	enterOldPw: 'Enter old password',
       	newPw: 'New Password',
       	enterNewPw: 'Enter the set password',
       	saveQrCode: 'Save QR code',
       	exNodeCode: 'node code',
       	exCreditCode: 'Credit Token',
       	exLink: 'Exclusive Link',
       	myPush: 'My Push',
       	myLeft: 'My left',
       	myRight: 'My right',
       	yesterdayNum: 'Yesterday\'s',
		todayNum: 'Today\'s',
       	teamNum: 'Team',
       	leftNum: 'Left Zone',
		"backTop": "Back Top",
       	rightNum: 'Right Zone',
       	profitRecord: 'Record',
       	teamList: 'Team List',
       	exchangeOutAccount: 'Out of Account',
       	outAccountId: 'Input out ID',
       	transferNum: 'Number of transfers',
       	enterTransferNum: 'Number of inputs',
       	transferOut: 'Transfer Out',
       	main: 'main',
       },
       wallet: {
       	activeTip1: 'Notice: enter credit token and pay',
       	activeTip2: 'Credit line, you can activate your account',
       	activeTip3: 'Notice: Pay',
       	activeTip4: 'Boost source, you can activate the sub account',
       	nodeCode: 'Node code(Optional)',
       	enterNodeCode: 'Enter the node code and select your area',
       	enterCreditCode: 'Enter a credit token and need it',
       	creditQuote: 'Credit line',
       	needPay: 'Need to pay',
       	help: 'Power source',
       	helpOr: 'Assistance source or',
       	active: 'Activate',
       	activeAccount: 'Activate Account',
       	plEnterCreditCode: 'Please enter a credit token',
       	aeraTitle: 'Select',
       	aeraLeft: 'Increase (left area)',
       	aeraRight: 'Minus (Right Zone)',
       	assetAdd: 'Asset Conversion',
       	powerList: ['Power A', 'Power B', 'Power C'],
       	activeTip: 'The credit token is a sign of community identity. It has barrier-free capacity and assets to exercise power in the Entropy chain network and various extended DAPPs. In the future, Entropy chain will also have various service privileges inside and outside the ecosystem, which are widely used on the Internet and even In the real economy.',
       	nowActive: 'immediately',
       	scan: 'scan it',
       	shoukuang: 'Receipt Code',
       	currentAccount: 'Current Account',
       	goOut: 'Exited, enjoy normal returns after reinvestment! ',
       	staticState: 'Static',
       	dynamicStatic: 'Dynamic',
       	assetWallet: 'Asset wallet',
       	qrCode: 'QR code',
		examinate: 'It is detected that your email and mobile phone are not bound, please bind'
       },
       walletAsset: {
       	"avalible": "Available",
       	"frezen": "Freeze",
       	recharge: 'Charge',
       	withdraw: 'Withdrawal',
       	exchange: 'transformation',
       	transfer: 'Rotate',
       	assetAccount: 'Asset',
       	powAccount: 'Bonus',
       	record: 'Financial Record',
       	filter: 'Filter',
       	notRecord: 'No record'
       },
       walletEx: {
       	from: 'from',
       	to: 'to',
       	transformNum: 'Number of transfers',
       	enterTransformNum: 'Please enter the number of transfers',
       	all: 'All',
       	balance: 'Balance',
       	rate: 'Exchange rate',
       	fee: 'Transaction Fee',
       	outNum: 'Residual snap-up volume',
       	exchange: 'Exchange',
       	safeTitel: 'Safe Authentication',
       	safePwd: 'Secure Password',
       	enterSafePwd: 'Enter password',
       	submit: 'Submit',
       	enterCoinnum: 'Enter exchange amount',
       },
       exchangeDetail: {
       	type: 'Type',
       	coin: 'Currency',
       	withdraw: 'Withdrawal',
       	amount: 'Amount',
       	formCoin: 'Exchange currency',
       	ex: 'Exchange',
       	exNum: 'Redemption Quantity',
       	exMoney: 'Exchange Amount',
       	time: 'Time',
       },
       walletHuazhuan: {
       	selectCoin: 'Select currency',
       	from: 'from',
       	to: 'to',
       	all: 'All',
       	avalible: 'Available',
       	fee: 'Transaction Fee',
       	balance: 'Balance',
       	transfer: 'Rotate',
       	enterNum: 'Please enter the number of strokes',
       	tfNum: 'Number of strokes',
       	tip: 'Only the assets can be transferred to the corresponding account to carry out transactions. There is no handling fee for transferring between accounts',
       	exportt: 'Go Out',
       	safeTitel: 'Safe Authentication',
       	safePwd: 'Secure Password',
       	enterSafePwd: 'Please enter a secure password',
       	submit: 'Submit',
       	enterCoinnum: 'Please enter the number of exchange currencies',
       	assetAccount: 'Asset Account',
       	OTCAccount: 'Bonus account',
       	notSupport: 'Switching is not currently supported'
       },
       walletRecharge: {
       	selectCoin: 'Choose assets',
       	chainType: 'Chain Type',
       	saveImg: 'Save to album',
       	rechargeAddress: 'Recharge Address',
       	copy: 'copy',
       	copyAddress: 'Copy Address',
       	tip1: 'Do not recharge any assets other than the currency to the above address, otherwise the assets will not be recovered. Minimum recharge amount ',
       	tip2: 'Deposits less than the minimum amount will not be credited and cannot be returned',
		tip3: 'Do not recharge any assets other than the currency to the above address, otherwise the assets will not be recovered. Minimum recharge amount.Deposits less than the minimum amount will not be credited and cannot be returned',
       	selectCode: 'Select QR code',
		needUSDT:'Need to recharge the amount of USDT',
		'remark':'remark',
		'remarkPlaceHold':'Please fill in the remarks',
		'exchangeRecord': 'exchange record',
		'showPayPic':'show',
		'uploadPic': 'upload',
		'complete': 'complete'
       },
       walletWithdraw: {
       	selectCoin: 'Select currency',
       	withdrawAddress: 'Charge Address',
       	enterUserID: 'Please enter a user ID',
       	enterAddress: 'Please enter a payment address ID',
       	num: 'Quantity',
       	enterWD1: 'Please enter the amount of withdrawal, minimum',
       	all: 'All',
       	avalible: 'Available',
       	fee: 'Transaction Fee',
       	minWD: 'Minimum withdrawal amount is',
       	minWD1: 'Please make sure the computer and browser are secure to prevent information from being tampered with or leaked.',
       	get: 'Estimated arrival',
       	wd: 'Withdrawal',
       	enterWDAdr: 'Please enter the withdrawal address',
       	enterWDNum: 'Please enter the amount of withdrawal',
       },
       ecologyDetail: {
       	avalible: 'Available balance',
       	record: 'Financial Record',
       	type: 'Type',
       	time: 'Time',
       	num: 'Quantity',
       	amount: 'Amount',
       	types: {
       		'1': 'Initial source',
       		'2': 'Boost Source',
       		'3': 'Entropy',
       		'4': 'Energy Storage Pool',
       		'a': 'Power A',
       		'b': 'Power B',
       		'c': 'Power C'
       	},
       	equivalent: 'Equivalent',
		tradeRecord:'tradeRecord',
		distributionRecord:'distributionRecord'
       },
       ecologyIndex: {
       	app: 'App Recommendation',
       	link1: 'Cross-chain asset conversion',
       	link2: 'Asset Deposit',
       	link3: 'Initial source subscription',
       	link4: 'Entropy Trading',
       	link5: 'USDF trading',
       	link6: 'Power Source',
       	browser: 'Browser',
       	inDevelopment: 'in development'
       },
       ecologyInitsource: {
       	type: 'Type',
       	title: 'Initial Subscription',
       	titleRight: 'Rule',
       	currentPrice: 'Current trade price: ',
       	join: 'Participate in the subscription',
       	buyAmount: 'Buy Amount',
       	avalible: 'Available',
       	help: '助力 源',
       	not: 'Not yet',
       	go: 'Go Get',
       	nowBuy: 'Buy Now',
       	get: 'Get',
       	startAccount: 'Initial source enters the subscription account',
       	myInits: 'My Subscription',
       	time: 'Time',
       	buyNum: 'Buy Quantity',
       	kcAmount: 'Deducted Amount',
       	safeVef: 'Safe Verification',
       	enterPwd: 'Please enter a secure password',
       	submit: 'Submit',
       	tipTitle: 'Friendship Tips',
       	tipText: 'Need to wait patiently for the queue time to expire, the entropy value will be bought automatically',
       	confirmTitle: 'Subscription Confirmation',
       	confirmText: 'Confirm subscription',
       	sAndDy: 'Static / dynamic recast ',
       	staticReinvestment: 'Static Reinvestment',
       	dyReinvestment: 'Dynamic Reinvestment',
       	staticBuy: 'Static subscription',
       	dyBuy: 'Dynamic Subscription'
       },
       ecologyPower: {
       	'link1': 'Initial source',
       	'link2': 'Boost Source',
       	'link3': 'Entropy',
       	'link4': 'Energy Storage Pool',
       },
       registerBackup: {
       	tip1: 'It is strongly recommended that you copy the mnemonic word on paper and keep it in a safe place only you know. Anyone who gets the mnemonic word can consume your digital assets. ',
       	tip2: 'Mnemonic words are used to restore your wallet. Losing them you will lose your wallet forever. ',
       	tip3: 'Please click your mnemonic in order to confirm that the backup mnemonic is correct. ',
       	tipCopy: 'Press and hold the mnemonic to copy it to the clipboard.',
       	next: 'Next',
       	enterAccount: 'Please enter an account name',
       	enterRule: 'Please enter 8-16 digits',
       	walletPwd: 'Wallet Password',
       	enterPwd: 'Duplicate password',
       	create: 'Create',
       	loopPwd: 'Please enter the password again',
       	pwdDiff: 'The passwords entered twice are inconsistent',
       	enterPhone: 'Please enter a phone',
       	enterEmail: 'Please enter your email account',
       	phoneErr: 'The format of the phone number is incorrect',
       	emailErr: 'Mailbox format error',
       	confirmSeed: 'Please confirm the mnemonic',
       	userId: 'Please enter user ID',
       	login: 'log in',
       	pressAndPaste: 'Long press to paste mnemonic',
       	paymentPassword: 'Payment password',
       	resurePw: 'Confirm payment password',
       	paymentPw: 'Please enter 8-16 digit payment password',
       	confirmPaymentPw: 'Enter the payment password again',
       	paymentpwdDiff: "Payment passwords entered twice are inconsistent",
       },
       registerIndex: {
       	exportAccount: 'Import Identity',
       	hasWallet: 'Already own wallet',
       	createAccount: 'Create Identity',
       	firstWallet: 'First use of wallet',
       	searchArea: 'Search Area',
       	cancel: 'Cancel',
       	toLogin: 'Already have an account, go to login',
       },
       registerRestore: {
       	helpWord: 'Mnemonic',
       	privateKey: 'Private Key',
       	copyKeystore: 'Copy and paste the content of the official keystore file into the input box',
       	enterPrivateKey: 'Enter Private Key into the input box',
       	enterHelpWord: 'Enter mnemonic words, separated by spaces',
       	keystoreContent: 'Keystore file content',
       	enterPrivateKey2: 'Enter the Private Key into the input box',
       	accountName: 'Account Name',
       	enterAccount: 'Enter account name',
       	pwd: 'Password',
       	enterKeyStore: 'EPlease enter the password of the wallet keystore file content',
       	enterKeystorePwd: 'Confirm Keystore password',
       	enterOldWalletKeystore: 'Confirm the password of the money source Keystore file',
       	setPwd: 'Set Password',
       	enterWalletPwd: 'Enter wallet password',
       	confirmPwd: 'Confirm Password',
       	twiceEnterPwd: 'Enter the wallet password again',
       	startExport: 'Start import',
       	enter: 'Fill in the content of the input box',
       	enterPwd: 'Enter password',
       	twicePwd: 'Enter the password again',
       	pwdDiff: 'The passwords entered twice are inconsistent',
       },
       trade: {
       	restNum: 'remaining sell entropy',
       	gu: 'Share',
       	myOrder: 'My Order',
       	amount: 'Amount',
       	cellPrice: 'Unit Price',
       	num: 'Amount',
       	tradeCenter: 'Trading Center',
       	all: 'All',
       	processing: 'In progress',
       	completed: 'Completed',
       	buy: 'I want to buy',
       	sell: 'I want to sell',
       	time: 'Time',
       	buyIn: 'Buy',
       	sellOut: 'Sell',
       	orderState: 'Order Status',
       	tradePrice: 'Trading price',
       	tradeAmount: 'Transaction Amount',
       	completeTime: 'Completion time',
       	queuingTime: 'Queue time',
       	starCredit: 'Star Credit',
       	tradingTotal: 'Total turnover',
       	tradengAvePrice: 'Average price',
       	tradingPrice: 'Transaction price',
       	tradingAmount: 'Volume',
       	bindMobile: 'Please bind mobile number first'
       },
       payment: {
       	"edit": "Edit",
       	"wechat": "Wechat",
       	"alipay": "Alipay",
       	"bank": "Bank Card",
       	"add": "Add",
       	"enterName": "Please enter a name",
       	"enterWechatAccount": "Please enter your WeChat account",
       	"addCode": "Add Receipt QR Code",
       	"pleaseAddCode": "Please add a payment QR code",
       	"save": "Save",
       	"linkType": "Link Type",
       	"enterAddress": "Please enter a payment address",
       	"enterBankNum": "Please enter your bank card number",
       	"enterBankName": "Please enter the account bank",
       	"enterBranch": "Please enter the bank branch",
       	"enterAlipay": "Please enter your Alipay account",
       	"chosePayment": 'Choose your payment method'
       },
       otc: {
       	orderRecord: 'Order Record',
       	myPending: 'Pending Order',
       	releasePending: 'Release Order',
       	unComplete: 'Incomplete',
       	completed: 'Completed',
       	stateUnpay: 'To be paid',
       	stateUnSure: 'To be confirmed',
       	tradeSucess: 'Transaction succeeded',
       	orderComplete: 'Order closed',
       	arbitrate: 'Arbitration',
       	arbitrateDetail: 'Arbitration details',
       	arbComplete: 'Arbitration completed',
       	arbitration: 'Arbitrating',
       	tradeTotal: 'Trade Total',
       	buyPending: 'My buy order',
       	sellPending: 'My sell order',
       	deleteText: "Delete",
       	sureDeletePending: 'Are you sure you want to delete the pending order? ',
       	needBuy: 'I want to buy',
       	needSell: 'I want to sell',
       	choseCoin: 'Choose a currency',
       	payment: 'Payment Method',
       	tradePrice: 'Trading price',
       	tradeAmount: 'Transaction Amount',
       	enterAmount: 'Please enter the number of transactions',
       	balance: 'Available Balance',
       	fee: 'Transaction Fee',
       	deleted: 'Deleted',
       	type: 'Type',
       	coin: 'Currency',
       	cancel: 'Cancel',
       	sureRelease: 'Confirm Release',
       	paymentTip: "You haven't added a payment method, you can't sell it temporarily, whether to add a payment method",
       	atLeast: 'Please select at least one payment method',
       	sellName: 'Seller Nickname',
       	buyName: 'Buyer Nickname',
       	orderNum: 'Order Number',
       	createOrderTime: 'Order time',
       	buyDetail: 'Buy Details',
       	sellDetail: 'Sell Details',
       	watingPay: 'Waiting for payment',
       	orderCancel: 'Order cancelled',
       	buyHasPay: 'The buyer has paid',
       	remain: 'Remaining',
       	screenShot: 'Receive Screenshot',
       	clickToView: 'Click to view',
       	recept: 'Confirm payment',
       	receptConfirm: 'Confirm receipt',
       	receptMoneyConfirm: 'Confirm that payment from buyer has been received',
       	aplyArbitration: 'Apply for arbitration',
       	aplyArbitrationConfirm: 'Are you sure you want to apply for arbitration? ',
       	tips: 'Tip',
       	tipContent: 'Please check the beneficiary account to confirm the amount of receipt',
       	checkbox: 'I have logged in to the payment account and confirmed that the payment was correct',
       	saveImg: 'Save Image',
       	saveSuccess: 'Save successfully',
       	saveFail: 'Save failed',
       	confirmAndCheck: 'Please check after you confirm',
       	pleasePay: 'Please pay',
       	timeTip1: 'Please be here',
       	timeTip2: 'Internal payment to seller',
       	tradeTip: 'Please pay in time',
       	openBank: 'Opening Bank',
       	bankName: 'Name',
       	bankNum: 'Bank Card Number',
       	bankBranch: 'Account Opening Branch',
       	receptAccount: 'Receiving Account',
       	receptAddress: 'Payment Address',
       	receptCode: 'Receipt QR Code',
       	note1: 'Conversion grants to buyers for profit',
       	note2: 'If you have transferred money to the seller, please be sure to click the "Mark as paid" button, otherwise you may cause financial loss. ',
       	onSure: 'Confirm',
       	payNote: 'Please confirm that you have paid to the seller, malicious clicks will directly freeze the account',
       	originator: 'Initiator of Arbitration',
       	arbitrator: 'Arbitee',
       	enterApply: 'Enter application request',
       	pleaseEnterApply: 'Please enter an application request',
       	uploadImg: 'Upload Image',
       	imgFormat: 'Please save the content of the photo is complete and clear, only supports JPG / PNG image format',
       	confirmSumit: 'Confirm Submit',
       	applySuccess: 'Application succeeded',
       	waitingNote: 'Please be patient, we will process it within 3 ~ 5 working days',
       	processComplete: 'Processing completed',
       	pending: 'Pending',
       	buyer: 'Buyer',
       	seller: 'Seller',
       	uploadPayImg: 'Upload payment screenshot',
       	onSurePay: 'Confirm payment',
       	uploadWarn: 'False uploads will directly freeze the account',
       	pleaseUpload: 'Please upload payment screenshot',
       	uploadTip: 'Please confirm that you have paid to the seller, false uploads will directly freeze the account',
       	uploadTip1: 'Upload payment screenshot after payment',
       	buySuccess: 'Buy Success',
       	sellSuccess: 'Sell successfully',
       	waitingRelease: 'Waiting for release',
       	contactWay: 'contact details'
       },
       v2: {
       	home: 'Home',
       	total: 'Total balance',
       	ecoBanner: 'Ecological construction',
       	ecoDec: 'Infinite Entropy Chain ，Infinite Value',
       	ecoItem1: 'Block Explorer',
       	ecoItem2: 'DAPP construction',
       	ecoItem3: 'I want to apply',
       	createConcept: 'Create a new concept',
       	notBuyTip: 'Unsubscribed, unable to participate in USDF trading!',
       	thirdplatform: 'Third-party platform',
       	thirdWallet: 'Third-party wallet',
       	activeTip: 'Activation prompt',
       	activeTipContent: 'After activating Entropy Chain, you can perform related operations.',
       },
       v2Eco: {
       	service: 'Energy center',
       	nodeApply: 'Node application',
       	applyInfo: 'Applicant Information',
       	applyName: 'applicant',
       	applyMobile: 'contact number',
       	applyEmail: 'Contact email',
       	dl: 'Download form',
       	xls1: 'Energy Center Application Form',
       	xls2: 'Node application form',
       	upload: 'Upload form',
       	baseInfo: 'Port protocol download',
       	nodeLevel: 'Apply for node level',
       	applyFee: 'Apply for node server pledge fee',
       	submit: 'submit',
       	enter: 'please enter',
       	error: 'wrong format',
       	node1: 'Master node',
       	node2: 'Secondary node',
       	node3: 'Small node',
       	type: 'Types of',
       	time: 'time',
       	result: 'result',
       	platform: 'platform',
       	wallet: 'wallet',
       	officalAddress: 'Official website address',
       	dlsuccess: 'download successful',
       	dlfail: 'download failed',
       	uploadFile: 'Please upload the form',
       	noAddress: 'No download address'
       },
       pro: {
       	showLang: 'Display language',
       	myShare: 'My share',
       	teamNum: 'Number of teams',
       	destroyNum: 'Destroy amount',
       	level: 'level',
       	totalAsset: 'Total assets',
       	safeTip: 'Safe reminder',
       	safeNote: 'In order to prevent the loss of assets caused by forgotten passwords, deleted apps or lost mobile phones, please be sure to back up mnemonic words',
       	backup: 'Back up now',
       	transfer: 'Transfer',
       	collect: 'Receive money',
       	tradeRecord: 'Trade record',
       	all: "All"
       },
       proHome: {
       	yestodayProfit: 'Yesterday mining revenue',
       	totalProfit: 'Cumulative income',
       	mySuanli: 'My hashrate',
       	dynSuanli: 'Dynamic computing power',
       	myDynSuanli: 'My dynamic computing power',
       	netSuanli: 'Current computing power of the entire network',
       	research: 'Destroy query',
       	tip1: 'Heavy attack',
       	tip2: 'What are you waiting for, hurry up and participate',
       	guide: 'Newbie Guide',
       	guideNote: "Having trouble with EntropyPro? Enter the beginner's guide for help ",
       	join: 'Mining',
       	myMachine: 'My miner',
       	sign: 'sign in',
       	class1: 'Video area',
       	class2: 'Audio Zone',
       	class3: 'Hundred Questions and Answers',
       	suanliRecord: 'Hash rate record',
       	systemInfo: 'System information',
       	systemNote: 'System announcement',
       	machineType: 'model',
       	level: 'level constant',
       	upgrade: 'Upgrade condition',
       	cumulative: 'cumulative destruction',
       	fee: 'Handling fee',
       	miningRecord: 'Mining record',
       	destroy: 'Destroy',
       	destroyRecord: 'Destroy record',
       	machineMall: 'Mine Machine Mall',
       	mallTip: 'Promote to get miners to participate in mining',
       	machineDetail: 'details',
       	apply: 'Application conditions',
       	share: 'Invite now',
       	shareNum: 'Invite',
       	person: '人',
       	money: 'amount',
       	minerFee: 'Miner fees',
       	enterAddress: "Receiving Address",
       	payAddress: 'Payment address',
       	tradeNum: 'Trading number',
       	block: 'Block'
       },
       sign: {
       	signed: 'Continuously signed in',
       	todaySigned: 'Signed today',
       	click: 'click to sign in',
       	record: 'Sign in record',
       	date1: 'Mon',
       	date2: 'Tues',
       	date3: 'wed',
       	date4: 'Thur',
       	date5: 'Fri',
       	date6: 'Sat',
       	date7: 'Sun',
       	day: 'day'
       },
       destroy: {
       	title: 'EntropyPro Destruction Record',
       	view: 'Destroy plan view',
       	updateTime: 'Data update time',
       	newNotice: 'Latest destruction announcement',
       	project: 'Destroy project',
       	time: 'Destroy time',
       	circle: 'Destroy cycle',
       	amount: 'Destroy amount',
       	amountTab: 'Quantity (number)',
       	address: 'Destroy address',
       	readMore: 'Click to view',
       	history: 'History cumulative destruction',
       	historyCart: 'History destruction overview',
       	dataDisclosure: 'Circulation data disclosure',
       	disclosureRecord: 'Circulation data disclosure record',
       	viewTab: 'View',
       	week: 'Weekly destruction'
       },
       v2Active: {
       	condition: 'Activation condition',
       	note: 'To open a contract transaction, the following conditions must be met',
       	mobileVal: 'Mobile verification',
       	valed: 'Verified',
       	unval: 'Unverified',
       	valFail: 'verification failed',
       	validate: 'Verify',
       	need: 'Need to deduct 1USDF as activation loss',
       	agree: 'I have understood and agreed',
       	toAgree: 'Please understand and agree first',
       	agreement: '"User Agreement"',
       	content: 'All content',
       	notActive: 'Not active at the moment',
       	confirm: 'OK and activate',
       	valToast: 'Please complete phone verification first'
       }
    },
    'zh-CN': {
        tab: {
        		ecology: '生態建設',
        		user: '我的',
        		trade: '交易',
        		wallet: '首頁'
        	},
        	"page": {
        		"news": "消息",
        		"createWallet": "創建錢包",
        		"backup": "備份助記詞",
        		"confirm": "確認助記詞",
        		"restore": "導入身份",
        		"power": "動力源",
        		"asset": "資產列表",
        		"creditcode": "授信令牌",
        		"nodecode": "節點碼",
        		"setting": "設置",
        		"about": "關於我們",
        		"walletActive": "激活賬戶",
        		"exchange": "跨鏈轉換",
        		"exchangeDetail": "詳情",
        		"userAccount": "賬戶管理",
        		"accountlist": "全部子賬戶",
        		"subAccount": "子賬戶",
        		"createAccount": "創建賬戶",
        		"userExchange": "兌換",
        		"feedBack": "消息中心",
        		"personal": "個人資料",
        		"safe": "安全中心",
        		"settingpw": "密碼設置",
        		settingPaypw: '支付密碼設置',
        		"team": "我的團隊",
        		"transfer": "互轉",
        		recordDetail: '成交明細',
				USDFExchange:'USDF兌換',
				exchangeRecord: '兌換記錄',
				USDFTransaction:'USDF交易'
        	},
        	"common": {
        		"unopen": "暫未開放",
        		"remenberTip": "友情提示",
        		"enterPw": "請輸入密碼",
        		"copySuccess": "已複製到剪切板",
        		"version": "版本",
        		"warmTip": "溫馨提示",
        		"safeTitle": "安全驗證",
        		"safePassword": "密碼",
        		loginPw: '登錄密碼',
        		"enterSafePwd": "請輸入安全密碼",
        		"submitBtn": "提交",
        		"pwVal": "密碼長度必須是8-16位",
        		"pwDiff": "兩次輸入的密碼不一致",
        		"refresh": "上拉顯示更多",
        		"loading": "正在加載...",
        		"noMore": "沒有更多數據了",
        		cancel: '取消',
        		confirm: '確定',
        		getCode: '獲取驗證碼',
        		waiting: '請耐心等待',
        		noCoin: '暫無可選幣種',
        		paymentPassword: '請輸入支付密碼',
        		unableModify: '不可修改',
        		settingPaymentFirst: '請先設置資金密碼'
        	},
        	"lang": {
        		"chose": "語言選擇",
        		"clearStore": "清除緩存",
        		"clearSuccess": "清除成功",
        		"cancel": "取消",
        		exit: '安全退出'
        	},
        	"user": {
        		"identManager": "身份管理",
        		"deleteText": "刪除",
        		"payment": "收款方式",
        		"paymentCode": "收款碼",
        		"creditCode": "授信令牌",
        		"nodeCode": "節點碼",
        		"copyAddress": "長按複製地址",
        		"aeed": "助記詞",
        		"outputKey": "導出私鑰",
        		"privateKey": "私鑰",
        		"output": "導出",
        		"outputSeed": "導出助記詞",
        		"deleteTip": "確定要刪除賬戶？",
        		"createSub": "創建子帳戶",
        		"switchConfirm": "確認要切換賬戶？",
        		"current": '當前',
        		"currentAccount": "當前賬戶",
        		"collectConfirm": "確認將所有子帳戶USDF收集至主帳戶？",
        		"viewAllAccount": "查看全部子賬戶",
        		"subAccountTip": "創建子帳戶需要激活方可完成創建，子帳戶將終身綁定到主帳戶，子帳戶的操作將通過主帳戶切換進入完成。並且子帳戶認購、創建金額全部由主帳戶的資金扣除。",
        		"oneStepCollect": "一鍵收集",
        		"usernameOrAddress": "賬戶名/地址",
        		"realSwitch": "輕觸賬戶進行切換",
        		"manager": "管理",
        		"otherOption": "其他操作",
        		"createAccount": "創建新賬戶",
        		"inputAccount": "導入賬戶",
        		"addressBook": "地址本",
        		"newCreate": "新建",
        		"addressDetail": "地址詳情",
        		"edit": "編輯",
        		"deleteAddress": "刪除地址",
        		"createAddress": "新建地址",
        		"save": "保存",
        		"enterAddress": "請輸入有效地址",
        		"addressName": "名稱",
        		"addressNote": "描述（選填）",
				"addressNoteDetail": "描述",
				"addressNameDetail": "地址",
        		"enterAddressName": "請輸入名稱",
        		"accountName": "賬戶名",
        		"enterAccountName": "請輸入賬戶名",
        		"walletPassword": "錢包密碼",
        		"enterWalletPw": "請輸入錢包密碼",
        		"confirmPw": "確認密碼",
        		"repeatEnterPw": "請重復輸入密碼",
        		"create": "創建",
        		"avalible": "可用",
        		"avalibleQuote": "可用額度",
        		"creditRecord": "授信記錄",
        		"interchange": "互轉",
        		"exchange": "兌換",
        		"fromText": "從",
        		"toText": "到",
        		"exchangeOutNum": "轉出數量",
        		"enteerExchangeNum": "請輸入轉出數量",
        		"all": "全部",
        		"balance": "餘額",
        		"rate": "匯率",
        		"question": "問題",
        		"serviceReplay": "客服回復",
        		"serviceNote": "客服留言",
        		"noReplay": "暫未回復",
        		"viewSubAccount": "查看子賬戶",
        		"myTeam": "我的團隊",
        		"relationship": "節點關係",
        		"accountMananger": "賬戶管理",
        		"safeCenter": "安全中心",
        		"contactUs": "聯繫客服",
        		"inviteFriend": "邀請好友",
        		"myLeftCode": "熵增節點碼",
        		"myRightCode": "熵減節點碼",
        		"level": "層級",
        		"leftCode": "熵增",
        		"rightCode": "熵減",
        		"copy": "複製",
        		"avatar": "頭像",
        		"nickname": "暱稱",
        		"enterNickname": "請輸入暱稱",
        		"mobile": "手機",
				"enterMobile":'請輸入手機號碼',
        		"email": "郵箱",
        		"modify": "修改",
        		"toBind": "去綁定",
        		"newsCenter": "消息中心",
        		"feedbackQuestion": "請輸入您要反饋的問題",
        		"feedbackContent": "請輸入您要反饋的內容和建議...",
        		"feedbackSubmit": "提交反饋",
				"moreMessage":'更多',
        		"completeInfo": "請輸入完整信息",
        		"valCode": "驗證碼",
        		"pleaseEnter": "請輸入",
        		"enterValCode": "請填寫驗證碼",
        		"confirm": "確認",
        		"mobileBinding": "手機綁定",
        		"emailBinding": "郵箱綁定",
        		"mobileError": "手機號格式錯誤",
        		"emailError": "郵箱格式錯誤",
        		"numCode": "請輸入6位驗證碼",
        		"oldPw": "舊密碼",
        		"enterOldPw": "請輸入舊密碼",
        		"newPw": "新的密碼",
        		"enterNewPw": "請輸入你要設置的密碼",
        		"saveQrCode": "保存二維碼",
        		"exNodeCode": "專屬節點碼",
        		"exCreditCode": "專屬授信令牌",
        		"exLink": "專屬邀請鏈接",
        		"myPush": "我的直推",
        		"myLeft": "熵增",
        		"myRight": "熵減",
        		"yesterdayNum": "昨日業績",
				"todayNum": "今日業績",
        		"teamNum": "團隊業績",
        		"leftNum": "熵增業績",
				"backTop": "回到頂部",
        		"rightNum": "熵減業績",
        		"profitRecord": "收益記錄",
        		"teamList": "團隊列表",
        		"exchangeOutAccount": "轉出賬戶",
        		"outAccountId": "請輸入轉出賬戶ID",
        		"transferNum": "划轉數量",
        		"enterTransferNum": "請輸入轉出數量",
        		"transferOut": "轉出",
        		"main": "主"
        	},
        	"wallet": {
        		"activeTip1": "須知：輸入授信令牌並支付",
        		"activeTip2": "授信額度，便可激活賬戶",
        		"activeTip3": "須知：支付",
        		"activeTip4": "助力源，便可激活子賬戶",
        		"nodeCode": "節點碼(選填)",
        		"enterNodeCode": "請輸入節點碼，選擇您的所在區",
        		"enterCreditCode": "請輸入授信令牌，並且需要",
        		"creditQuote": "授信額度",
        		"needPay": "需要支付",
        		"help": "助力源",
        		"helpOr": "助力源或",
        		"active": "激活",
        		"activeAccount": "激活賬戶",
        		"plEnterCreditCode": "請輸入授信令牌",
        		"aeraTitle": "選擇分區",
        		"aeraLeft": "熵增(左區)",
        		"aeraRight": "熵減(右區)",
        		"assetAdd": "資產折合",
        		"powerList": ["動力A", "動力B", "動力C"],
        		"activeTip": "授信令牌是社區身份的標識，在Entropy chain網絡及各類延展DAPP中具有無障礙的通行能力和資產行使權力，未來Entropy chain還將在生態圈內外擁有各類服務特權，廣泛用於互聯網乃至實體經濟中。",
        		"nowActive": "立即激活",
        		"scan": "掃一掃",
        		"shoukuang": "收款碼",
        		currentAccount: '當前賬戶',
        		goOut: '已出局，復投後享正常收益！',
        		staticState: '靜態',
        		dynamicStatic: '動態',
        		assetWallet: '資產錢包',
        		qrCode: '二維碼',
				"examinate":'檢測到妳未綁定郵箱和手機，請綁定'
        	},
        	"walletAsset": {
        		"avalible": "可用",
        		"frezen": "凍結",
        		"recharge": "充幣",
        		"withdraw": "提幣",
        		"exchange": "轉換",
        		"transfer": "划轉",
        		"assetAccount": "資產賬戶",
        		"powAccount": "資金賬戶",
        		"record": "財務記錄",
        		"filter": "篩選",
        		"notRecord": "暫無記錄"
        	},
        	"walletEx": {
        		"from": "從",
        		"to": "到",
        		"transformNum": "轉出數量",
        		"enterTransformNum": "請輸入轉出數量",
        		"all": "全部",
        		"balance": "餘額",
        		"rate": "匯率",
        		"fee": "手續費",
        		"outNum": "剩餘搶購量",
        		"exchange": "跨鏈轉換",
        		"safeTitel": "安全驗證",
        		"safePwd": "安全密碼",
        		"enterSafePwd": "請輸入安全密碼",
        		"submit": "提交",
        		"enterCoinnum": "請輸入兌換幣種數量"
        	},
        	"exchangeDetail": {
        		"type": "類型",
        		"coin": "幣種",
        		"withdraw": "提現",
        		"amount": "金額",
        		"formCoin": "兌換幣種",
        		"ex": "兌換",
        		"exNum": "兌換數量",
        		"exMoney": "兌換金額",
        		"time": "時間"
        	},
        	"walletHuazhuan": {
        		"selectCoin": "選擇幣種",
        		"from": "從",
        		"to": "到",
        		"all": "全部",
        		"avalible": "可用",
        		"fee": "手續費",
        		"balance": "餘額",
        		"transfer": "划轉",
        		"enterNum": "請輸入划出數量",
        		"tfNum": "划轉數量",
        		"tip": "只有將資產划轉到對應賬戶才可以進行交易，賬戶間划轉不收取手續費",
        		"exportt": "轉出",
        		"safeTitel": "安全驗證",
        		"safePwd": "安全密碼",
        		"enterSafePwd": "請輸入安全密碼",
        		"submit": "提交",
        		"enterCoinnum": "請輸入兌換幣種數量",
        		"assetAccount": "資產賬戶",
        		"OTCAccount": "獎金賬戶",
        		notSupport: '暫不支持切換'
        	},
        	"walletRecharge": {
        		"selectCoin": "選擇資產",
        		"chainType": "鏈類型",
        		"saveImg": "保存到相冊",
        		"rechargeAddress": "錢包地址",
        		copy: '複製',
        		"copyAddress": "複製地址",
        		"tip1": "請勿向上述地址充值任何非該幣種資產，否則資產將不可找回。最小充值金額",
        		"tip2": "小於最小金額的充值將不會入賬，且無法退回",
				"tip3": "請按照匯率換算準確充值，否則將無法審核通過，有誤請聯系客服。請勿向上述地址充值任何非ERC20_USDT幣種，否則資產將不可找回。 最小充值金額100，小於最小金額的充值將無法入賬，且無法退回",
        		selectCode: '選擇二維碼',
				'needUSDT':'需充值USDT數量',
				'remark':'備註',
				'remarkPlaceHold':'請填写备注信息',
				'exchangeRecord': '兌換記錄',
				'showPayPic':'查看憑證',
				'uploadPic':'上傳憑證',
				'complete':'完成訂單'
				
				
        	},
        	"walletWithdraw": {
        		"selectCoin": "選擇幣種",
        		"withdrawAddress": "充幣地址",
        		"enterUserID": "請輸入用戶ID",
        		"enterAddress": "請輸入收款地址",
        		"num": "數量",
        		"enterWD1": "請輸入提幣數量, 最少",
        		"all": "全部",
        		"avalible": "可用",
        		"fee": "手續費",
        		"minWD": "最小提幣數量為",
        		"minWD1": "請務必確認電腦及瀏覽器安全，防止信息被篡改或洩露。",
        		"get": "預計到賬",
        		"wd": "提幣",
        		"enterWDAdr": "請輸入提幣地址",
        		"enterWDNum": "請輸入提幣數量"
        	},
        	"ecologyDetail": {
        		"avalible": "可用餘額",
        		"record": "財務記錄",
        		"type": "類型",
        		"time": "時間",
        		"num": "數量",
        		"amount": "金額",
        		"types": {
        			"1": "初始源",
        			"2": "助力源",
        			"3": "熵值",
        			"4": "儲能池",
        			"a": "動力A",
        			"b": "動力B",
        			"c": "動力C"
        		},
        		equivalent: '折合',
				tradeRecord:'交易記錄',
				distributionRecord:'配送記錄'
        	},
        	"ecologyIndex": {
        		"app": "應用推薦",
        		"link1": "跨鏈資產轉換",
        		"link2": "資產充值",
        		"link3": "初始源認購",
        		"link4": "熵值交易",
        		"link5": "USDF交易",
        		"link6": "動力源",
        		browser: '瀏覽器',
        		inDevelopment: '正在開發中'
        	},
        	"ecologyInitsource": {
        		type: '類型',
        		"title": "初始源認購",
        		"titleRight": "規則",
        		"currentPrice": "當前交易價格：",
        		"join": "參與認購",
        		"buyAmount": "購買金額",
        		"avalible": "可用",
        		"help": "助力源",
        		"not": "還沒有",
        		"go": "去獲取",
        		"nowBuy": "立即購買",
        		"get": "可獲得",
        		"startAccount": "初始源進入認購賬戶",
        		"myInits": "我的認購",
        		"time": "時間",
        		"buyNum": "購買數量",
        		"kcAmount": "扣除金額",
        		"safeVef": "安全驗證",
        		"enterPwd": "請輸入安全密碼",
        		"submit": "提交",
        		"tipTitle": "友情提示",
        		"tipText": "需耐心等待排隊時間到期，將自動買入熵值",
        		"confirmTitle": "認購確認",
        		"confirmText": "確認認購",
        		"sAndDy": "靜/動態復投",
        		"staticReinvestment": "靜態復投",
        		"dyReinvestment": "動態復投",
        		"staticBuy": "靜態認購",
        		"dyBuy": "動態認購"
        	},
        	"ecologyPower": {
        		"link1": "初始源",
        		"link2": "助力源",
        		"link3": "熵值",
        		"link4": "儲能池"
        	},
        	"registerBackup": {
        		"tip1": "強烈建議你將助記詞抄寫在紙上並保存在只有你知道的安全地方，任何人得到助記詞都可以消費你的數字資產。",
        		"tip2": "助記詞用於恢復你的錢包，丟失他們你將永遠失去錢包。",
        		"tip3": "請按順序點擊你的助記詞，以便確認備份助記詞的正確。",
        		"tipCopy": '長按下方助記詞，可複製到剪貼板。',
        		"next": "下一步",
        		"enterAccount": "請輸入賬戶名",
        		enterRule: '請輸入8-16位',
        		"walletPwd": "錢包密碼",
        		"enterPwd": "重復輸入密碼",
        		"create": "創建",
        		"loopPwd": "請再次輸入密碼",
        		"pwdDiff": "兩次輸入的密碼不一致",
        		"enterPhone": "請輸入手機",
        		"enterEmail": "請輸入郵箱賬號",
        		"phoneErr": "手機號格式錯誤",
        		"emailErr": "郵箱格式錯誤",
        		confirmSeed: '請確認助記詞',
        		userId: '請輸入用戶ID',
        		login: '登錄',
        		pressAndPaste: '長按可粘貼助記詞',
        		paymentPassword: '支付密碼',
        		resurePw: '確認支付密碼',
        		paymentPw: '請輸入8-16位支付密碼',
        		confirmPaymentPw: '重復輸入支付密碼',
        		paymentpwdDiff: "兩次輸入的支付密碼不一致",
        	},
        	"registerIndex": {
        		"exportAccount": "導入身份",
        		"hasWallet": "已擁有錢包",
        		"createAccount": "創建身份",
        		"firstWallet": "第一次使用錢包",
        		"searchArea": "搜索地區",
        		"cancel": "取消",
        		toLogin: '已有賬號，去登錄',
        	},
        	"registerRestore": {
        		"helpWord": "助記詞",
        		"privateKey": "私鑰",
        		"copyKeystore": "複製粘貼官方錢包的Keystore文件內容至輸入框",
        		"enterPrivateKey": "輸入Private Key 至輸入框",
        		"enterHelpWord": "輸入助記詞單詞，並使用空格分隔",
        		"keystoreContent": "Keystore文件內容",
        		"enterPrivateKey2": "輸入私鑰 Private Key 至輸入框內",
        		"accountName": "賬戶名稱",
        		"enterAccount": "請輸入賬戶名稱",
        		"pwd": "密碼",
        		"enterKeyStore": "請輸入錢包Keystore文件內容的密碼",
        		"enterKeystorePwd": "確認Keystore 密碼",
        		"enterOldWalletKeystore": "請確認錢原Keystore文件內容的密碼",
        		"setPwd": "設置密碼",
        		"enterWalletPwd": "請輸入錢包密碼",
        		"confirmPwd": "確認密碼",
        		"twiceEnterPwd": "請再次輸入錢包密碼",
        		"startExport": "開始導入",
        		"enter": "請填寫輸入框內容",
        		"enterPwd": "請輸入密碼",
        		"twicePwd": "請再次輸入密碼",
        		"pwdDiff": "兩次輸入的密碼不一致"
        	},
        	"trade": {
        		"restNum": "當前剩餘賣出熵值",
        		"gu": "ETF",
        		"myOrder": "我的訂單",
        		"amount": "數量",
        		"cellPrice": "單價",
        		"num": "金額",
        		"tradeCenter": "交易中心",
        		"all": "全部",
        		"processing": "進行中",
        		"completed": "已完成",
        		"buy": "我要買",
        		"sell": "我要賣",
        		"time": "時間",
        		"buyIn": "買入",
        		"sellOut": "賣出",
        		"orderState": "訂單狀態",
        		"tradePrice": "交易價格",
        		"tradeAmount": "交易數量",
        		"completeTime": "完成時間",
        		"queuingTime": "排隊時間",
        		starCredit: '星信用',
        		tradingTotal: '成交總額',
        		tradengAvePrice: '成交均價',
        		tradingPrice: '成交價',
        		tradingAmount: '成交量',
        		bindMobile: '請先綁定手機號',
				
        	},
        	"payment": {
        		"edit": "編輯",
        		"wechat": "微信",
        		"alipay": "支付寶",
        		"bank": "銀行卡",
        		"add": "添加",
        		"enterName": "請輸入姓名",
        		"enterWechatAccount": "請輸入您的微信賬號",
        		"addCode": "添加收款二維碼",
        		"pleaseAddCode": "請添加收款二維碼",
        		"save": "保存",
        		"linkType": "鏈類型",
        		"enterAddress": "請輸入收款地址",
        		"enterBankNum": "請輸入銀行卡號",
        		"enterBankName": "請輸入開戶銀行",
        		"enterBranch": "請輸入開戶行分行",
        		"enterAlipay": "請輸入您的支付寶賬號",
        		"chosePayment": "選擇收款方式",
        	},
        	otc: {
        		orderRecord: '訂單記錄',
        		myPending: '我的掛單',
        		releasePending: '發佈掛單',
        		unComplete: '未完成',
        		completed: '已完成',
        		stateUnpay: '待支付',
        		stateUnSure: '待確認',
        		tradeSucess: '交易成功',
        		orderComplete: '訂單關閉',
        		arbitrate: '仲裁',
        		arbitrateDetail: '仲裁詳情',
        		arbComplete: '仲裁完成',
        		arbitration: '仲裁中',
        		tradeTotal: '交易總額',
        		buyPending: '我發佈的買單',
        		sellPending: '我發佈的賣單',
        		deleteText: '刪除',
        		sureDeletePending: '確認要刪除掛單？',
        		needBuy: '我要購買',
        		needSell: '我要出售',
        		choseCoin: '選擇幣種',
        		payment: '支付方式',
        		tradePrice: '交易價格',
        		tradeAmount: '交易數量',
        		enterAmount: '請輸入交易數量',
        		balance: '可用餘額',
        		fee: '手續費',
        		deleted: '已刪除',
        		type: '類型',
        		coin: '幣種',
        		cancel: '取消',
        		sureRelease: '確認發佈',
        		paymentTip: '您還未添加支付方式，暫時不能出售，是否去添加支付方式',
        		atLeast: '請選擇至少一種支付方式',
        		sellName: '賣家暱稱',
        		buyName: '買家暱稱',
        		orderNum: '訂單號',
        		createOrderTime: '下單時間',
        		buyDetail: '買入詳情',
        		sellDetail: '賣出詳情',
        		watingPay: '等待買家付款',
        		orderCancel: '訂單已取消',
        		buyHasPay: '買家已付款',
        		remain: '剩餘',
        		screenShot: '收款截圖',
        		clickToView: '點擊查看',
        		recept: '確定收款',
        		receptConfirm: '確認收款',
        		receptMoneyConfirm: '確認已收到買家的付款',
        		aplyArbitration: '申請仲裁',
        		aplyArbitrationConfirm: '確認要申請仲裁？',
        		tips: '提示',
        		tipContent: '請查看收款賬戶，確認收款金額',
        		checkbox: '我已登錄收款賬號，並確認收款無誤',
        		saveImg: '保存圖片',
        		saveSuccess: '保存成功',
        		saveFail: '保存失敗',
        		confirmAndCheck: '請確認後勾選',
        		pleasePay: '請付款',
        		timeTip1: '請在',
        		timeTip2: '內付款給賣家',
        		tradeTip: '請及時付款',
        		openBank: '開戶銀行',
        		bankName: '開戶人姓名',
        		bankNum: '銀行卡號',
        		bankBranch: '開戶支行',
        		receptAccount: '收款賬號',
        		receptAddress: '收款地址',
        		receptCode: '收款二維碼',
        		note1: '轉換賦能贈送給買家獲利',
        		note2: '如您已向賣家轉賬付款,請務必點擊「標記為已支付」按鈕,否則有可能造成資金損失。',
        		onSure: '確認',
        		payNote: '請確認您已向賣家付款,惡意點擊將直接凍結賬戶',
        		originator: '發起仲裁方',
        		arbitrator: '被仲裁方',
        		enterApply: '輸入申請請求',
        		pleaseEnterApply: '請輸入申請請求',
        		uploadImg: '上傳圖片',
        		imgFormat: '請保存照片的內容完整並清晰可見，僅支持JPG/PNG圖片格式',
        		confirmSumit: '確認提交',
        		applySuccess: '申請成功',
        		waitingNote: '請耐心等待，我們會在3~5個工作日內處理',
        		processComplete: '處理完成',
        		pending: '待處理',
        		buyer: '買家',
        		seller: '賣家',
        		uploadPayImg: '上傳支付截圖',
        		onSurePay: '確認付款',
        		uploadWarn: '虛假上傳將直接凍結賬戶',
        		pleaseUpload: '請上傳付款截圖',
        		uploadTip: '請確認您已向賣家付款,虛假上傳將直接凍結賬戶',
        		uploadTip1: '付款後請上傳付款截圖',
        		buySuccess: '買入成功',
        		sellSuccess: '賣出成功',
        		waitingRelease: '等待賣家放行',
        		contactWay: '聯繫方式'
        	},
        	v2: {
        		home: '首頁',
        		total: '總餘額',
        		ecoBanner: '實時掌握 生態建設',
        		ecoDec: '無限的熵鏈 無限的價值',
        		ecoItem1: '區塊瀏覽器',
        		ecoItem2: '第三方DAPP建設',
        		ecoItem3: '我要申請',
        		createConcept: '創建全新理念',
        		notBuyTip: '未認購，無法參與USDF交易！',
        		thirdplatform: '第三方平台',
        		thirdWallet: '第三方錢包',
        		activeTip: '激活提示',
        		activeTipContent: '激活Entropy Chain後，可進行相關操作。',
        	},
        	v2Eco: {
        		service: '能量中心',
        		nodeApply: '節點申請',
        		applyInfo: '申請人信息',
        		applyName: '申請人',
        		applyMobile: '聯繫電話',
        		applyEmail: '聯繫郵箱',
        		dl: '下載表格',
        		xls1: '能量中心申請表格',
        		xls2: '節點申請表格',
        		upload: '上傳表格',
        		baseInfo: '端口協議下載',
        		nodeLevel: '申請節點等級',
        		applyFee: '申請節點服務器質押費用',
        		submit: '提交',
        		enter: '請輸入',
        		error: '格式錯誤',
        		node1: '主節點',
        		node2: '副節點',
        		node3: '小節點',
        		type: '類型',
        		time: '時間',
        		result: '結果',
        		platform: '平台',
        		wallet: '錢包',
        		officalAddress: '官網地址',
        		dlsuccess: '下載成功',
        		dlfail: '下載失敗',
        		uploadFile: '請上傳表格',
        		noAddress: '暫無下載地址'
        	},
        	pro: {
        		showLang: '顯示語言',
        		myShare: '我的分享',
        		teamNum: '團隊人數',
        		destroyNum: '銷毀量',
        		level: '等級',
        		totalAsset: '總資產',
        		safeTip: '安全提醒',
        		safeNote: '為防止忘記密碼、刪除App或丟失手機等情況導致資產損失，請務必備份助記詞',
        		backup: '立即備份',
        		transfer: '轉賬',
        		collect: '收款',
        		tradeRecord: '交易記錄',
        		all: "全部"
        	},
        	proHome: {
        		yestodayProfit: '昨日挖礦收益',
        		totalProfit: '累計收益',
        		mySuanli: '我的算力',
        		dynSuanli: '動態算力',
        		myDynSuanli: '我的動態算力',
        		netSuanli: '當前全網算力',
        		research: '銷毀查詢',
        		tip1: '重磅來襲',
        		tip2: '你還在等什麼，趕快來參與吧',
        		guide: '新手指南',
        		guideNote: '使用EntropyPro遇到難題？進入新手指南尋找幫助',
        		join: '參與挖礦',
        		myMachine: '我的礦機',
        		sign: '每日簽到',
        		class1: '視頻區',
        		class2: '音頻區',
        		class3: '百問答題',
        		suanliRecord: '算力記錄',
        		systemInfo: '系統信息',
        		systemNote: '系統公告',
        		machineType: '礦機型號',
        		level: '等級常數',
        		upgrade: '升級條件',
        		cumulative: '累計銷毀',
        		fee: '手續費',
        		miningRecord: '挖礦記錄',
        		destroy: '銷毀',
        		destroyRecord: '銷毀記錄',
        		machineMall: '礦機商城',
        		mallTip: '推廣即可獲得礦機參與挖礦',
        		machineDetail: '礦機詳情',
        		apply: '申請條件',
        		share: '立即邀請',
        		shareNum: '邀請',
        		person: '人',
        		money: '金額',
        		minerFee: '礦工費用',
        		enterAddress: '收款地址',
        		payAddress: '付款地址',
        		tradeNum: '交易號',
        		block: '區塊'
        	},
        	sign: {
        		signed: '已連續簽到',
        		todaySigned: '今日已簽',
        		click: '點擊簽到',
        		record: '簽到記錄',
        		date1: '一',
        		date2: '二',
        		date3: '三',
        		date4: '四',
        		date5: '五',
        		date6: '六',
        		date7: '日',
        		day: '天'
        	},
        	destroy: {
        		title: 'EntropyPro銷毀記錄',
        		view: '銷毀方案查看',
        		updateTime: '數據更新時間',
        		newNotice: '最新銷毀公示',
        		project: '銷毀項目',
        		time: '銷毀時間',
        		circle: '銷毀週期',
        		amount: '銷毀數量',
        		amountTab: '數量（個）',
        		address: '銷毀地址',
        		readMore: '點擊查看',
        		history: '歷史累計銷毀',
        		historyCart: '歷史銷毀概覽',
        		dataDisclosure: '流通數據披露',
        		disclosureRecord: '流通數據披露記錄',
        		viewTab: '查看',
        		week: '周銷毀'
        	},
        	v2Active: {
        		condition: '激活條件',
        		note: '開通合約交易，需滿足以下條件',
        		mobileVal: '手機驗證',
        		valed: '已驗證',
        		unval: '未驗證',
        		valFail: '驗證失敗',
        		validate: '驗證',
        		need: '需要扣除1USDF作為激活損耗',
        		agree: '我已理解並同意',
        		toAgree: '請先理解並同意',
        		agreement: '《用戶協議》',
        		content: '的全部內容',
        		notActive: '暫不激活',
        		confirm: '確定並激活',
        		valToast: '請先完成手機驗證'
        	}

    }
}